### ISSUE TITLE
C++11なのかC++17なのか

### ISSUE THREAD

**Issue by yumetodo** [nokotan/DxLibForHTML5-VSCode#1]
はじめまして。DxLibの掲示板からきました。まだ中身を読み始めた段階ですが、一点。

https://github.com/nokotan/DxLibForHTML5-VSCode/blob/684a26f186e4de13dcddba29e25f5d36382d02e9/.vscode/tasks.json#L18

https://github.com/nokotan/DxLibForHTML5-VSCode/blob/684a26f186e4de13dcddba29e25f5d36382d02e9/.vscode/c_cpp_properties.json#L17

IntelliSenseの設定とビルドの設定が整合していないように思えます。どちらが意図したものでしょうか？

**Comment by nokotan** [comment]
指摘ありがとうございます。
特に意図はありませんでした。(em++のサンプルで c++11 となっているもの、vs codeのデフォルトタスクがc++17になっていたことから)
ただ、IntelliSenseの設定とビルドの設定に不整合があるとビルド時に混乱させかねないので、c++17で統一して修正させていただきます。
